// Code generated by generators/resource/main.go; DO NOT EDIT.

package sample_test

import (
	"regexp"
	"testing"

	"github.com/eVisionSoftware/axiom/terraform-provider-axiom/internal/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccAxiomSampleResourceType_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Axiom::Sample::ResourceType", "axiom_sample_resource_type", "test")

	td.ResourceTest(t, []resource.TestStep{
		{
			Config:      td.EmptyConfig(),
			ExpectError: regexp.MustCompile("Missing required argument"),
		},
	})
}
