// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/singular-data-source/main.go -data-source axiom_sample_resource_type -cfschema ../service/cloudformation/schemas/Axiom_Sample_ResourceType.json -package sample ../axiom/sample/resource_type_singular_data_source_gen.go ../axiom/sample/resource_type_singular_data_source_gen_test.go

package provider

import (
	_ "github.com/eVisionSoftware/axiom/terraform-provider-axiom/internal/axiom/sample"
)
